src/EMM/UserBundle/Entity/User.php
<?php

namespace EMM\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;

/**
 * User
 *
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass="EMM\UserBundle\Entity\UserRepository")
 * @UniqueEntity("username")
 * @UniqueEntity("email")
 * @ORM\HasLifecycleCallbacks()
 */
class User implements AdvancedUserInterface, \Serializable
{

    /**
     * @ORM\OneToMany(targetEntity="Task", mappedBy="user")
     */
    protected $tasks;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=50)
     * @Assert\NotBlank()
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=100)
     * @Assert\NotBlank()
     */
    private $nombre;

    /**
     * @var string
     *
     * @ORM\Column(name="appaterno", type="string", length=100)
     * @Assert\NotBlank()
     */
    private $appaterno;


    /**
     * @var string
     *
     * @ORM\Column(name="apmaterno", type="string", length=100)
     * @Assert\NotBlank()
     */
    private $apmaterno;

    /**
     * @var string
     *
     * @ORM\Column(name="rfc", type="string", length=20)
     * @Assert\NotBlank()
     */
    private $rfc;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=100)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="role", type="string", columnDefinition="ENUM('ROLE_ADMIN', 'ROLE_USER')",length=50)
     * @Assert\NotBlank()
     * @Assert\Choice(choices = {"ROLE_ADMIN", "ROLE_USER"})
     */
    private $role;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updatedAt;


    public function __construct()
    {
        $this->tasks = new ArrayCollection();
        $this->isActive=true;
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string 
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return User
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get nombre
     *
     * @return string 
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set apmaterno
     *
     * @param string $apmaterno
     * @return User
     */
    public function setApmaterno($apmaterno)
    {
        $this->apmaterno = $apmaterno;

        return $this;
    }

    /**
     * Get apmaterno
     *
     * @return string 
     */
    public function getApmaterno()
    {
        return $this->apmaterno;
    }

    /**
     * Set appaterno
     *
     * @param string $appaterno
     * @return User
     */
    public function setAppaterno($appaterno)
    {
        $this->appaterno = $appaterno;

        return $this;
    }

    /**
     * Get appaterno
     *
     * @return string 
     */
    public function getAppaterno()
    {
        return $this->appaterno;
    }

    /**
     * Set rfc
     *
     * @param string $rfc
     * @return User
     */
    public function setRfc($rfc)
    {
        $this->rfc = $rfc;

        return $this;
    }

    /**
     * Get rfc
     *
     * @return string 
     */
    public function getRfc()
    {
        return $this->rfc;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set role
     *
     * @param string $role
     * @return User
     */
    public function setRole($role)
    {
        $this->role = $role;

        return $this;
    }

    /**
     * Get role
     *
     * @return string 
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     * @return User
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * Get isActive
     *
     * @return boolean 
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return User
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return User
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        $this->createdAt = new \DateTime();
    }
    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new \DateTime();
    }

    public function getRoles()
    {
        return array($this->role);

    }   

        public function getSalt()
    {

        return null;
    } 
    public function eraseCredentials()
    {

    }

    /**
     * Add tasks
     *
     * @param \EMM\UserBundle\Entity\Task $tasks
     * @return User
     */
    public function addTask(\EMM\UserBundle\Entity\Task $tasks)
    {
        $this->tasks[] = $tasks;
        return $this;
    }
    /**
     * Remove tasks
     *
     * @param \EMM\UserBundle\Entity\Task $tasks
     */
    public function removeTask(\EMM\UserBundle\Entity\Task $tasks)
    {
        $this->tasks->removeElement($tasks);
    }
    /**
     * Get tasks
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTasks()
    {
        return $this->tasks;
    }
    
    public function getFullName()
    {
        return $this->nombre . " " . $this->appaterno. " ". $this->apmaterno;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            $this->isActive
            ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->username,
            $this->password,
            $this->isActive
            ) = unserialize($serialized);
    }

    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->isActive;
    }

}

src/EMM/UserBundle/Controller/UserController.php
<?php

namespace EMM\UserBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\FormError;
use EMM\UserBundle\Entity\User;
use EMM\UserBundle\Form\UserType;

class UserController extends Controller
{
    public function homeAction()
    {
        return $this->render('EMMUserBundle:User:home.html.twig');
    }

    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        //$users = $em->getRepository('EMMUserBundle:User')->findAll();

        $dql = "SELECT u FROM EMMUserBundle:User u ORDER BY u.id DESC";
        $users = $em->createQuery($dql);

        $paginator=$this->get('knp_paginator');
        $pagination=$paginator->paginate(
        	$users, $request->query->getInt('page', 1),
        	3
        	);

        //crear la variable deleteform ajax
        $deleteFormAjax = $this->createCustomForm(':USER_ID', 'DELETE', 'emm_user_delete');

        return $this->render('EMMUserBundle:User:index.html.twig',array('pagination'=>$pagination, 'delete_form_ajax'=>$deleteFormAjax->createView()));


    }

    public function addAction()
    {

    	$user = new User();
    	$form= $this->createCreateForm($user);

    	return $this->render('EMMUserBundle:User:add.html.twig', array('form'=>$form->createView()));

    }

    private function createCreateForm(User $entity)
    {
    	$form=$this->createForm(new UserType(), $entity, array(
    		'action'=>$this->generateUrl('emm_user_create'), 
    		'method'=>'POST'
    		));
    	return $form;
    }

    public function createAction(Request $request)
    {
    	$user = new User();
    	$form = $this->createCreateForm($user);
    	$form->handleRequest($request);

    	if($form->isValid())
    	{

    		$password = $form->get('password')->getData();

    		$passwordConstraint = new Assert\NotBlank();
    		$errorList = $this->get('Validator')->validate($password,$passwordConstraint);
    		if (count($errorList)==0) {
    			
    		$encoder = $this->container->get('security.password_encoder');
    		$encoded = $encoder->encodePassword($user, $password);

    		$user->setPassword($encoded);

    		$em = $this->getDoctrine()->getManager();
    		$em->persist($user);
    		$em->flush();

    		$this ->addFlash('mensaje', 'El usuario ha sido creado. ');

    		return $this->redirectToRoute('emm_user_index');
    		}

    		else{
    			$errorMessage= new FormError($errorList[0]->getMessage());
    			$form->get('password')->addError($errorMessage);
    		}

    	}
    	return $this->render('EMMUserBundle:User:add.html.twig', array('form'=>$form->createView()));
    }

    public function editAction($id)
    {
    	$em= $this->getDoctrine()->getManager();
    	$user=$em->getRepository('EMMUserBundle:User')->find($id);

    	if(!$user)
    	{
    		$messageException = $this->get('translator')->trans('User not found. ');
    		throw $this->createNotFuoundException($messageException);
    		
    	}

    	$form = $this->createEditForm($user);

    	return $this->render('EMMUserBundle:User:edit.html.twig', array('user' => $user, 'form' =>$form->createView()));

    }

    private function createEditForm(User $entity)
    {
    	$form = $this->createForm(new UserType(), $entity, array('action'=>$this->generateUrl('emm_user_update', array('id'=>$entity->getId())), 'method'=>'PUT'));

    	return $form;
    }

    public function updateAction($id, Request $request)
    {
    	$em = $this->getDoctrine()->getManager();

    	$user= $em->getRepository('EMMUserBundle:User')->find($id);

    	if(!$user)
    	{
    		$messageException = $this->get('translator')->trans('User not found. ');
    		throw $this->createNotFuoundException($messageException);
    		
    	}

    	$form = $this->createEditForm($user);
    	$form->handleRequest($request);

    	if ($form->isSubmitted() && $form->isValid())
    	{
    		$password = $form->get('password')->getData();
    		
    		if(!empty($password))
    		{
    			$encoder =$this->container->get('security.password_encoder');
    			$encoded =$encoder->encodePassword($user, $password);
    			$user->setPassword($encoded);
    		}
    		else
    		{
    			$recoverPass = $this->recoverPass($id);

    			$user->setPassword($recoverPass[0]['password']);
    		}
    		if ($form->get('role')->getData()=='ROLE_ADMIN') {
    			$user->setIsActive(1);
    			# code...
    		}

    		$em->flush();

    		$successMessage= $this->get('translator')->trans('The User has been modified');
    		$this->addFlash('mensaje', $successMessage);
    		return $this->redirectToRoute('emm_user_index', array('id'=>$user->getId()));
    	}

    	return $this->render('EMMUserBundle:User:edit.html.twig', array('user'=>$user, 'form'=>$form->createView()));
    }

    private function recoverPass($id)
    {
    	$em = $this->getDoctrine()->getManager();
    	$query =$em->createQuery(
    		'SELECT u.password
    		FROM EMMUserBundle:User u
    		WHERE u.id = :id'
    		)->setParameter('id', $id);

    	$currentPass =$query->getResult();

    	return $currentPass;
    }
    

    public function viewAction($id)
    {
    	$repository = $this->getDoctrine()->getRepository('EMMUserBundle:User');

    	$user =$repository->find($id);
    	//$user = $repository->findOneById($id);

    	if(!$user)
    	{
    		$messageException =  $this->get('translator')->trans('User not found. ');
    		throw $this->createNotFoundException($messageException);
    		
    	}

    	$deleteForm = $this->createCustomForm($user->getId(), 'DELETE', 'emm_user_delete');


    	//return new Response('Usuario: '.$user->getUsername().' con email: '.$user->getEmail());

    	return $this->render('EMMUserBundle:User:view.html.twig', array('user' => $user, 'delete_form' => $deleteForm->createView()));
    }


    public function deleteAction(Request $request, $id)
    {
    	$em= $this->getDoctrine()->getManager();

    	$user= $em->getRepository('EMMUserBundle:User')->find($id);

//verificar si el usuario existe
    	if(!$user)
    	{
    		$messageException =  $this->get('translator')->trans('User not found. ');
    		throw $this->createNotFoundException($messageException);
    		
    	}

    	$allUsers= $em->getRepository('EMMUserBundle:User')->findAll();
    	$countUsers= count($allUsers);

    	//$form =$this->createDeleteForm($user);
    	$form = $this->createCustomForm($user->getId(), 'DELETE', 'emm_user_delete');
    	$form->handleRequest($request);

    	//validar que el usuario se halla eliminado correctamente
    	if($form->isSubmitted() && $form->isValid())
    	{
    		if($request->isXMLHttpRequest())
    		{
    			$res = $this->deleteUser($user->getRole(), $em, $user);

    			return new Response(

    				json_encode(array('removed'=> $res['removed'], 'message'=>$res['message'], 'countUsers'=>$countUsers)),
    				200,
    				array('Content-Type'=>'application/json')
    				);
    		}

    		$res = $this->deleteUser($user->getRole(), $em, $user);

    		$this->addFlash($res['alert'], $res['message']);
    		return $this->redirectToRoute('emm_user_index');
    	}

    }

    private function deleteUser($role, $em, $user)
    {
    	if($role=='ROLE_USER')
    	{
    		$em->remove($user);
    		$em->flush();
    		$message = $this->get('translator')->trans('The user has been deleted.');
    		$removed=1;
    		$alert='mensaje';
    	}
    	elseif ($role =='ROLE_ADMIN') {
    		$message = $this->get('translator')->trans('The user could not be delete.');
    		$removed = 0;
    		$alert = 'error';
    	}

    	return array('removed'=>$removed, 'message'=>$message, 'alert'=>$alert);
    }

    //crear la función createCustomForm

    private function createCustomForm($id, $method, $route)
    {
    	return $this->createFormBuilder()
    		->setAction($this->generateUrl($route, array('id'=>$id)))
    		->setMethod($method)
    		->getForm();
    }

    public function articlesAction($page)
    {
    	return new Response('Este es mi artículo '. $page);
    }


}

src/EMM/UserBundle/Resources/views/User/add.html.twig
{% extends 'layout.html.twig' %}

{% block body %}

	{{ parent() }}
	<div class="main container">
		<div class="row well">
			<div class="col-md-6">
				<div class="page-header">
					<h2>{% trans %}New user{% endtrans %}</h2>
				</div>
			{{ form_start(form, { 'attr' : {'novalidate': 'novalidate', 'role': 'form'} }) }}

			<div class="form-group">
				{{ form_label(form.username) }}
				{{ form_widget(form.username, { 'attr': {'class': 'form-control', 'placeholder': 'Tu username'} }) }}
				<span class="text-danger">{{ form_errors(form.username) }}</span>
			</div>

			<div class="form-group">
				{{ form_label(form.nombre) }}
				{{ form_widget(form.nombre, { 'attr': {'class': 'form-control', 'placeholder': 'Tu nombre'} }) }}
				<span class="text-danger">{{ form_errors(form.nombre) }}</span>
			</div>

			<div class="form-group">
				{{ form_label(form.appaterno) }}
				{{ form_widget(form.appaterno, { 'attr': {'class': 'form-control', 'placeholder': 'Tu appaterno'} }) }}
				<span class="text-danger">{{ form_errors(form.appaterno) }}</span>
			</div>
			
			<div class="form-group">
				{{ form_label(form.apmaterno) }}
				{{ form_widget(form.apmaterno, { 'attr': {'class': 'form-control', 'placeholder': 'Tu apmaterno'} }) }}
				<span class="text-danger">{{ form_errors(form.apmaterno) }}</span>
			</div>			
			
			<div class="form-group">
				{{ form_label(form.rfc) }}
				{{ form_widget(form.rfc, { 'attr': {'class': 'form-control', 'placeholder': 'Tu rfc'} }) }}
				<span class="text-danger">{{ form_errors(form.rfc) }}</span>
			</div>
			
			<div class="form-group">
				{{ form_label(form.email) }}
				{{ form_widget(form.email, { 'attr': {'class': 'form-control', 'placeholder': 'Tu email'} }) }}
				<span class="text-danger">{{ form_errors(form.email) }}</span>
			</div>
			
			<div class="form-group">
				{{ form_label(form.password) }}
				{{ form_widget(form.password, { 'attr': {'class': 'form-control', 'placeholder': 'Tu password'} }) }}
				<span class="text-danger">{{ form_errors(form.password) }}</span>
			</div>
			
 			<div class="form-group">
			        {{ form_label(form.role) }}
			        {{ form_widget(form.role, {'attr': {'class': 'form-control'}}) }}
			        <span class="text-danger">{{ form_errors(form.role) }}</span>
			    </div>

				<div class="checkbox">
				    <label>
						{{ form_widget(form.isActive) }}{% trans %}Active{% endtrans %}
						<span class="text-danger">{{ form_errors(form.isActive) }}</span>
				    </label>
				</div>
			</fieldset>

		    <p>
		        {{ form_widget(form.save, {'label' : 'Create user', 'attr': {'class': 'btn btn-success'}}) }}
		    </p>                

			{{ form_end(form) }}
		</div>
	</div>
</div>
{% endblock %}

src/EMM/UserBundle/Resources/views/User/edit.html.twig
{% extends 'layout.html.twig' %}


{% block body %}
    {{ parent() }}

	<div class="main container">
		<div class="row well">
			<div class="col-md-6">
				<div class="page-header">
					<h2>Edit user</h2>
				</div>
				{{ form_start(form, {'attr': {'novalidate': 'novalidate', 'role' : 'form'}}) }}
				<h4 class="text-danger">{{ form_errors(form) }}</h4>
				<fieldset>
			<div class="form-group">
				{{ form_label(form.username) }}
				{{ form_widget(form.username, { 'attr': {'class': 'form-control', 'placeholder': 'Tu username'} }) }}
				<span class="text-danger">{{ form_errors(form.username) }}</span>
			</div>

			<div class="form-group">
				{{ form_label(form.nombre) }}
				{{ form_widget(form.nombre, { 'attr': {'class': 'form-control', 'placeholder': 'Tu nombre'} }) }}
				<span class="text-danger">{{ form_errors(form.nombre) }}</span>
			</div>

			<div class="form-group">
				{{ form_label(form.apmaterno) }}
				{{ form_widget(form.apmaterno, { 'attr': {'class': 'form-control', 'placeholder': 'Tu apmaterno'} }) }}
				<span class="text-danger">{{ form_errors(form.apmaterno) }}</span>
			</div>			

			<div class="form-group">
				{{ form_label(form.appaterno) }}
				{{ form_widget(form.appaterno, { 'attr': {'class': 'form-control', 'placeholder': 'Tu appaterno'} }) }}
				<span class="text-danger">{{ form_errors(form.appaterno) }}</span>
			</div>
			
			<div class="form-group">
				{{ form_label(form.rfc) }}
				{{ form_widget(form.rfc, { 'attr': {'class': 'form-control', 'placeholder': 'Tu rfc'} }) }}
				<span class="text-danger">{{ form_errors(form.rfc) }}</span>
			</div>
			
			<div class="form-group">
				{{ form_label(form.email) }}
				{{ form_widget(form.email, { 'attr': {'class': 'form-control', 'placeholder': 'Tu email'} }) }}
				<span class="text-danger">{{ form_errors(form.email) }}</span>
			</div>
			
			<div class="form-group">
				{{ form_label(form.password) }}
				{{ form_widget(form.password, { 'attr': {'class': 'form-control', 'placeholder': 'Tu password'} }) }}
				<span class="text-danger">{{ form_errors(form.password) }}</span>
			</div>
			
 			<div class="form-group">
			        {{ form_label(form.role) }}
			        {{ form_widget(form.role, {'attr': {'class': 'form-control'}}) }}
			        <span class="text-danger">{{ form_errors(form.role) }}</span>
			    </div>

				<div class="checkbox">
				    <label>
						{{ form_widget(form.isActive) }}{% trans %}Active{% endtrans %}
						<span class="text-danger">{{ form_errors(form.isActive) }}</span>
				    </label>
				</div>
					</fieldset>

				    <p>
				        {{ form_widget(form.save, {'label' : 'Update user', 'attr': {'class': 'btn btn-success'}}) }}
				    </p>

				{{ form_end(form) }}
			</div>
		</div>
	</div>
{% endblock %}

src/EMM/UserBundle/Resources/views/User/home.html.twig
{% extends 'layout.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('public/css/style.css') }}">
{% endblock %}

{% block body %}
	{{ parent() }}
	<div class="container">
		<h2 class="text-center">
		BIENVENIDO
		{% if app.user.role == 'ROLE_ADMIN' %}
			ADMINISTRADOR
		{% elseif app.user.role == 'ROLE_USER' %}
			USUARIO
		{% endif %}
		:
		{{ app.user.fullName }}
		( {{ app.user.username }} )
		</h2>
	</div>
{% endblock %}

src/EMM/UserBundle/Resources/views/User/index.html.twig
{% extends 'layout.html.twig' %}


{% block body %}
	{{ parent() }}

	{# Progress bar #}
	<div class="progress no-border hidden" id="delete-progress">
		<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
			<span class="sr-only">Loading...</span>
		</div>
	</div>

	{{ include('EMMUserBundle:User:message/success.html.twig') }}
	{{ include('EMMUserBundle:User:message/danger.html.twig') }}
	<div class="container">
		<div class="col-md-12">
			<div class="page-header margin-none">
			<h2 class="padding-none">{% trans %}User{% endtrans %}</h2>
			</div>
			<div class="table-responsive">
			Total Records: <span id="total">{{ pagination.getTotalItemCount }}</span>
			<table class="table table-striped table-hover">
				<thead>
				<tr>
					<th>{{ knp_pagination_sortable(pagination, 'Username'|trans, 'u.username') }}</th>
					<th>{{ knp_pagination_sortable(pagination, 'Nombre', 'u.nombre') }}</th>
					<th>{{ knp_pagination_sortable(pagination, 'Apellido Paterno', 'u.appaterno') }}</th>
					<th>{{ knp_pagination_sortable(pagination, 'Email', 'u.email') }}</th>
					<th>{{ knp_pagination_sortable(pagination, 'Role', 'u.role') }}</th>
					<th>{{ knp_pagination_sortable(pagination, 'Created', 'u.createdAt') }}</th>
					<th>{{ knp_pagination_sortable(pagination, 'Updated', 'u.updatedAt') }}</th>
					<th>Actions</th>
				</tr>
				</thead>
				<tbody>
					{% for user in pagination %}

		<tr data-id="{{ user.id }}">
			<td>{{ user.username }}</td>
			<td>{{ user.nombre }}</td>
			<td>{{ user.appaterno }}</td>
			<td>{{ user.email }}</td>
			<td>
			{% if user.role=='ROLE_ADMIN' %}
				<strong>Administrador</strong>
			{% elseif user.role=='ROLE_USER' %}
				<strong>Usuario</strong>
			{% endif %}
			</td>
			<td>{{ user.createdAt|date('d-m-Y H:i') }}</td>
			<td>{{ user.updatedAt|date('d-m-Y H:i') }}</td>
			<td>
				<a href="{{ path('emm_user_view', {id: user.id}) }}" class="btn btn-sm btn-info">View</a>
				<a href="{{ path('emm_user_edit', {id: user.id}) }}" class="btn btn-sm btn-primary">Edit</a>
				<a href="#" class="btn btn-sm btn-danger btn-delete">Delete</a>
			</td>
		</tr>

	{% endfor %}
				</tbody>
			</table>
			{# display navigation #}
			<div class="navigation">
				{{ knp_pagination_render(pagination) }}
			</div>	
			</div>
		</div>
	</div>

	{{ include('EMMUserBundle:User:forms/form.html.twig',{form: delete_form_ajax, message: 'Are you sure?'|trans, id:'form-delete', with_submit: false}) }}
{% endblock %}

{% block javascripts %}
{{ parent() }}
	<script src="{{ asset('bundles/emmuser/js/delete-user.js') }}"></script>
{% endblock %}